#!/bin/bash

TODAY=`date +%Y-%m-%d`  # like --iso-8601, but macOS compatible

if [ "$1" ]
then
	comment="$1-$TODAY"
	file="id_$comment"
else
	comment="`whoami`@`hostname`-$TODAY"
	file="id_ed25519"
fi
ssh-keygen -t ed25519 -C "$comment" -f "$file"
