#!/usr/bin/env python

def print_keys(path):
	try:
		f = file(path)
	except IOError, (errno, strerror):
		if errno == 2:	# ENOENT
			return
		raise

	print path + ':'
	for line in f:
		print '\t' + line.split()[-1]

def main():
	homes = [line.split(':')[5] for line in file('/etc/passwd')]
	for h in homes:
		print_keys(h + '/.ssh/authorized_keys')

if __name__ == '__main__':
	main()
